# configurations to build and test on every pull request
# each entry is a mapping with:
# - config: a string encoded list containing the docker image name and any number of build options.
# - The build options are `mpi`, `tbb`, `llvm`, `nomd`, and `nohpmc`.
unit_test_configurations:
- config: "[clang14_py310, mpi, tbb, llvm]"
- config: "[gcc12_py310]"
- config: "[gcc12_py310, nomd]"
- config: "[gcc12_py310, nohpmc]"
- config: "[gcc12_py310, nomd, nohpmc]"
- config: "[cuda116_gcc9_py38, mpi, llvm]"
- config: "[cuda116_gcc9_py38]"


# Configurations on which to run longer validation tests. Must be a subset of
# `unit_test_configurations`
validate_configurations:
- config: "[clang14_py310, mpi, tbb, llvm]"
- config: "[gcc12_py310]"
- config: "[cuda116_gcc9_py38, mpi, llvm]"
- config: "[cuda116_gcc9_py38]"

# Configurations to build and test only rarely, such as just before a release.
# There should be no overlap between this list and `unit_test_configurations`
release_test_configurations:
- config: "[clang13_py310, llvm]"
- config: "[clang12_py310, llvm]"
- config: "[clang11_py310, llvm]"
- config: "[gcc11_py310]"
- config: "[gcc10_py310]"
- config: "[cuda115_gcc9_py38, mpi, llvm]"
- config: "[cuda114_gcc9_py38, mpi, llvm]"
- config: "[cuda113_gcc9_py38, mpi, llvm]"
- config: "[cuda112_gcc9_py38, mpi, llvm]"
- config: "[cuda111_gcc9_py38, mpi, llvm]"
- config: "[cuda10_gcc7_py37, llvm]"
- config: "[clang10_py38, llvm]"
- config: "[gcc9_py38]"
- config: "[clang9_py38]"
- config: "[clang8_py38]"
- config: "[clang7_py38]"
- config: "[gcc8_py37]"
- config: "[gcc7_py37]"
- config: "[clang6_py37]"
- config: "[gcc7_py36]"
